### ISSUE TITLE
I'd really like to use Fenrus, but...

### ISSUE THREAD

**Issue by BaerHub** [revenz/Fenrus#206]
I cannot manage to get it working correctly.
Ive installed it via Docker compose:
```
services:
  fenrus:
    image: revenz/fenrus
    container_name: Fenrus
    environment:
      - TZ=Europe/Vienna
    volumes:
      - data:/app/data
      - images:/app/wwwroot/images
    restart: unless-stopped
    networks:
      npm_network:
volumes:
  data:
  images:
networks:
  npm_network:
    external: true
```

- Home Assistant API does not work. 
- Portainer API does not work.
- Adding iCal Calendar does not work.
- No documentation at all.
- Logs say nothing but wasting 30mb a day.

if you could help me correctly setup Fenrus, i'd be motivated to donate some
